### ISSUE TITLE
get() is too slow in cluster mode

### ISSUE THREAD

**Issue by amazingWu** [Grokzen/redis-py-cluster#228] opened 2017-11-08 09:45 UTC
my redis cluster has 6 nodes
I used the following code to test, but some key was too slow, >20s

```
import random
from rediscluster import *


def make_string():
    seed = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_"
    sa = []
    for i in range(35):
        sa.append(random.choice(seed))
    salt = ''.join(sa)
    return salt


redis_nodes = [{'host': 'xx.xx.xx.157', 'port': 7000},
               {'host': 'xx.xx.xx.157', 'port': 7001},
               {'host': 'xx.xx.xx.157', 'port': 7002},
               {'host': 'xx.xx.xx.157', 'port': 7003},
               {'host': 'xx.xx.xx.157', 'port': 7004},
               {'host': 'xx.xx.xx.157', 'port': 7005}
               ]


redisconn = StrictRedisCluster(startup_nodes=redis_nodes)
for i in range(1000):
    key = make_string()
    print(str(key))
    value = redisconn.get(key)
    print(value)
```

**Comment by Grokzen** [comment] 2017-11-08 09:48
Are you sure you do not exhaust your systems RNG data pool by doing this kind of operation?

Also you have to provide more data regarding what exactly is slow becuase from experience it do not look like the library code would be the reason why. Please do more analysis and provide more details regarding what steps in your code that is slow and if the timings is really in the .get() operation or in some other part of the code. I can't really work with this issue report.

**Comment by amazingWu** [comment] 2017-11-08 10:02
I have try it many times on different computers and systems. 
It shows getting some key will be very slow if the key doesn't exist in redis.
such as:
  get('123') is fast.
  get('123456') is very slow

It seems most of time is occupied by connectting to redis. 
I install it by pip3, should I use the lasted code to reinstall?



```
from rediscluster import *


redis_nodes = [{'host': 'xx.xx.xx.157', 'port': 7000},
               {'host': 'xx.xx.xx.157', 'port': 7001},
               {'host': 'xx.xx.xx.157', 'port': 7002},
               {'host': 'xx.xx.xx.157', 'port': 7003},
               {'host': 'xx.xx.xx.157', 'port': 7004},
               {'host': 'xx.xx.xx.157', 'port': 7005}
               ]
redisconn = StrictRedisCluster(startup_nodes=redis_nodes)
reidsconn.get('123456')
```

**Comment by Grokzen** [comment] 2017-11-08 11:43
If there is raw connection problems then it might be something local on your system. I have experience from doing must more operations then what you are showing without any problems what so ever.

Unless you can provide much more detailed tracing and code profiling that shows that there is some issue in the code, i would have to close this one as `unable to reproduce` because it works as expected on my machine and probably many other.

You could also try to look into the internals to see if  you have some major redirection issues inside the lib or not based on your cluster state as that could be a issue. But if we are talking about 20+ seconds it feels like DNS lookups the timeout or some other major network issue on your local machine.

**Comment by Grokzen** [comment] 2017-11-23 12:08
@amazingWu any update on this?

**Closed** 2017-12-18 13:25 UTC
