### ISSUE TITLE
connection redis cluster  frequently will have a RedisClusterException!

### ISSUE THREAD

**Issue by HatBoy** [Grokzen/redis-py-cluster#173] opened 2016-12-22 08:53 UTC
this is my Code:

```
import rediscluster

startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]
while True:
    client1 = rediscluster.StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
    print(client1.ping())
```

when I run the code will thrown an Exception,like this

```
Traceback (most recent call last):
  File "D:/Code/Pycharm/DBApp3/RTask/test.py", line 19, in <module>
    client1 = rediscluster.StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
  File "C:\Python\Python35\lib\site-packages\rediscluster\client.py", line 163, in __init__
    **kwargs
  File "C:\Python\Python35\lib\site-packages\rediscluster\connection.py", line 98, in __init__
    self.nodes.initialize()
  File "C:\Python\Python35\lib\site-packages\rediscluster\nodemanager.py", line 240, in initialize
    raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.
```

I find I can not connection redis cluster  frequently, it will thrown an Exception. Why?thank you

**Comment by Grokzen** [comment] 2016-12-22 14:28
@HatBoy do you get this on every try you make or do you get this after a while and running this script?

What i am thinking is that becuase you just spamm creating new cluster instances you fill up some open connection limit or something and that cause this to happen. The reason why this happens is that when you first create a cluster instance you try to determine the cluster configuration by calling on one of the nodes you specefied as startup_nodes and you ask it `CLUSTER NODES` i think it is.

If you would put a sleep 1 second after each ping, do you still get this error?

The only other error that cause this is that you do not have a cluster that is reachable on `127.0.0.1:7000`

**Comment by HatBoy** [comment] 2016-12-24 08:49
@Grokzen I get this after while and running this script, and I find the error is beacuse by nodemanager.py 178 line,
`cluster_slots = r.execute_command("cluster", "slots")`
when excute this code ,sometimes it can not get value, then I get a exception.why?

**Comment by Grokzen** [comment] 2016-12-24 11:18
@HatBoy I already specefied atleast 2 cases in my previous reply what could be the problem. 

I modefied your example to the following and i ran it for ~5000 itterations with 0 exceptions or problems to connect. Please try the script yourself and reply on what itteration this fails for you.

```
# Script, tested with python 3.4, redis-py 2.10.5
import rediscluster

startup_nodes = [{"host": "127.0.0.1", "port": "7000"}]
i = 0

while True:
    client1 = rediscluster.StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
    print(i, client1.ping())
    i += 1
```

and it outputed to this line with no problems

```
5000 {'172.17.0.2:7000': True, '172.17.0.2:7002': True, '172.17.0.2:7003': True, '172.17.0.2:7001': True, '172.17.0.2:7004': True, '172.17.0.2:7005': True}
```

There is no problems with the code, there is however a big probability that there is a problem with your redis-cluster installation. If you get a failure on the very first itteration then your startup nodes is bad and you can't connect to your instance. You can verify that you can connect to it by running telnet to it `127.0.0.1:7000` and get a established connection.

The other case could be that you hit some problem with the redis code it self and you have a crash or bug triggered in the redis code that cause your cluster to crash out and then ofc the client can't connect to the cluster. To verify this case just try to trigger the bug by running the client code and when you hit the exception you verify that you have a running cluster of all nodes and that you are able to connect to it and receive a accurate cluster setup by running  `CLUSTER NODES` or `CLUSTER INFO`.

Other metadata you shold provide to me is the following:
 - What python version are you running?
 - What version of the redis-py-cluster code are you running?
 - What versino of redis are you running
 - Method of running the redis cluster, inside docker, virtualbox, other machine etc.

If you can't provide more information/details then i can't help you because i can't reproduce the problem and the most likley cause is on your side and not in the code and i will have to close this issue as invalid.

**Comment by Grokzen** [comment] 2016-12-24 16:04
Another thing i thought of is that what you are observing is the intended code logic. If you are unable to connect or get a accurate view of your cluster when you create the instance of your `StrictRedisCluster` class. That is raises an exception is indeed intended.

**Comment by HatBoy** [comment] 2016-12-26 01:37
@Grokzen ,
1.My Python version is 3.5.1
2.redis-py-cluster  version is 1.3.3
3.redis cluster version is 3.2.3
4.I runing the redis cluster is Centos6.8, LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch, 
and I find I runing the client code on my Win7 system it will have the exception, but I runing the same code on my vmware Ubuntu16.04 not have the exception, I also find the exception case by  the code 
`cluster_slots = r.execute_command("cluster", "slots")`
on nodemanager.py 178 line,
so, I change my code is 
`
while True:
    client1 = rediscluster.StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
    print(client1.ping())
    print(client1.execute_command("cluster", "slots"))
    print(client1.scard('renrening'))
`
when run the execute_command method ,will have the exception:
`Traceback (most recent call last):
  File "D:/Code/Pycharm/DBApp3/RTask/test.py", line 23, in <module>
    print(client1.execute_command("cluster", "slots"))
  File "C:\Python\Python35\lib\site-packages\rediscluster\utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "C:\Python\Python35\lib\site-packages\rediscluster\client.py", line 367, in execute_command
    raise ClusterError('TTL exhausted.')
rediscluster.exceptions.ClusterError: TTL exhausted.`

**Comment by Grokzen** [comment] 2016-12-26 01:48
@HatBoy you do not have to repeat a third time where the exception come from.

I would like to get 3 other pieces of data from you becuase i think i know what the issue is.

1. The IP address of your windows machine
2. The IP address that you are running your cluster on (if that is the same machine)
3. If you can from a machine that can connect, please use redis-cli or this python client and manually execute this redis command `CLUSTER NODES` and paste the entire output here. This is the most important part acctually.

I have seen this problem before and with the data above i think i can narrow it down exactly and solve this problem.

**Comment by HatBoy** [comment] 2016-12-26 04:35
@Grokzen I running cluser on different machine,I execute the redis command:(I change the port to 8888)
`redis-cli -c -h X.X.X.X -p 8888 cluster nodes`
reture this result:
`
0f856e86125287ef3bc7d949e2778f53f5ecfbb4 X.X.X.X:8888 master - 0 1482726349130 4 connected 12288-16383
78efaddce08a7f5d8f2a4b2848bd862a65aca8b5 X.X.X.X:8888 master - 0 1482726348128 3 connected 8192-12287
b5b739f9af4fb4e401d57001212f64def7c46ce1 X.X.X.X:8888 master - 0 1482726345123 2 connected 4096-8191
cfff0a587bf80ebc30e6757824d36658228c6637 X.X.X.X:8888 myself,master - 0 0 1 connected 0-4095
`
thank you

**Comment by Grokzen** [comment] 2016-12-26 13:27
Well ok, that did not help anything that you hid the IP addresses. Unless they wore your public IP internet addresses it would not be anything bad with showing them.

But anyway i can explain what happens and why it breaks becuase i have seen this many times.

The TLDR version is that redis is announcing wrong IP addresses to your clients.

The long version. When you create a redis-cluster, all the nodes in the cluster will track a IP address that they will use to announce where they are and what IP address that redis itself uses to connect to all other nodes. The important thing here is to note that this is what _redis_ use and not what any other clients use to connect to any of the nodes in the cluster.

The problem with this approach by redis is that there is cases and some setups where if you run all nodes on the very same machine then you get into a case where all redis nodes can and will talk to eachother over lets say 127.0.0.1:8888 becuase all nodes is on the same machine. Then it tracks that IP:port address internally and when a client asks for `CLUSTER NODES`, redis happily returns that all nodes is located at 127.0.0.1:8888 for all clients. The problem is that if you are on another machine then you can't really connect to 127.0.0.1:8888 becuase you do not have the service running on that machine. That is why you are seeing that your script works on the machine that you run your cluster on but not on your windows machine.

The only solution to this case is to get redis to track another more public IP address that can be used to announce to all clients so that all clients can connect. I think the only way you can do right now is that whey you initialize your cluster and you tell all nodes to meet, you specify a IP:PORT address for it to use. Instead of using something like 127.0.0.1:8888 you should really be using the machines external/public IP address that other machines can connect to, for example 192.168.0.123 if you have that IP network in your infrastructure.

The only other way this could manifest is that your redis machines track a IP address that your windows machines can't resolve for any reason, but that is then only a network problem inside your infrastructure and that is not something i can help with.

The only support that exists in this library to combat this problem is that you have to define ALL nodes as startup nodes with their public ip addresses and then use the kwargs flag into StrictRedisClsuter that tells it to NOT do a `CLUSTER NODES` lookup when it initializes the client class. By doing this way the client ingores what redis says and it goes with the data you are providing yourself. This way is however not reccomended becuase if any cluster nodes crashes or changes IP or is unreachable for any reason, all clients will stop working until you reinialize them fully with a new cluster setup. In normal cases the client would deal with this by itself when the cluster returns `ASK & MOVED` errors internally.

**Comment by Grokzen** [comment] 2016-12-26 19:16
@HatBoy I am going to close this one now becuase there is no more info/help that can be provided to you to solve this problem. You should be able to solve it/understand what the problems is based on my previous post about the announcement IP from redis. The client behaves properly and this is not a _bug_ in the code. Things might just be very unclear about what is happening and the internal errors lacks abit of information.

**Closed by Grokzen** 2016-12-26 19:16 UTC
