### ISSUE TITLE
Intermittent KeyError from get_master_node_by_slot

### ISSUE THREAD

**Issue by melinath** [Grokzen/redis-py-cluster#287] opened 2018-10-17 22:54 UTC
We're using redis-py-cluster with some success in local dev, but users are intermittently getting a KeyError from get_master_node_by_slot, because the slot isn't set in `nodes.slots`.

**Comment by melinath** [comment] 2018-10-17 23:03
When I try to connect directly to redis using redis-cli I get CLUSTERDOWN errors, which makes me think the issue might lie with the docker container

**Comment by Grokzen** [comment] 2018-10-17 23:36
Do you not get a exception from this code? https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L379 It would make much more sense that redis would raise up a ClusterDown error back to the client and it would spit out that back to your code. That is what should happen if the error is when you run a command.

Do you maybe have a full stack trace of the error you are getting that you can share? Also when this happens, can you debug the variable `nodes.slots` to see what is actually inside the datastruct at the point of the error?

**Comment by melinath** [comment] 2018-10-18 16:33
I'll try to get you a stack trace. Fun thing, sometimes the same people getting KeyErrors are getting ClusterDown errors as well.

**Comment by melinath** [comment] 2018-10-18 17:03
```
Django Version: 1.11.12
Python Version: 2.7.12

Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File ".../common/handlers/wsgi.py" in inner
  77.         response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/utils/deprecation.py" in __call__
  142.             response = self.process_response(request, response)

File ".../common/middleware/session.py" in process_response
  63.                 response

File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/middleware.py" in process_response
  58.                             request.session.save()

File ".../common/session_backends.py" in save
  41.             if not self.redis_store.exists(self.session_key):

File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/cache.py" in exists
  71.         return session_key and (self.cache_key_prefix + session_key) in self._cache

File "/usr/local/lib/python2.7/dist-packages/django/core/cache/backends/base.py" in __contains__
  203.         return self.has_key(key)

File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py" in _decorator
  32.             return method(self, *args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django_redis/cache.py" in has_key
  124.         return self.client.has_key(*args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/django_redis/client/default.py" in has_key
  475.             return client.exists(key)

File "/usr/local/lib/python2.7/dist-packages/redis/client.py" in exists
  951.         return self.execute_command('EXISTS', name)

File "/usr/local/lib/python2.7/dist-packages/rediscluster/utils.py" in inner
  101.                 return func(*args, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/rediscluster/client.py" in execute_command
  361.                     node = self.connection_pool.get_node_by_slot(slot)

File "/usr/local/lib/python2.7/dist-packages/rediscluster/connection.py" in get_node_by_slot
  338.         return self.get_master_node_by_slot(slot)

File "/usr/local/lib/python2.7/dist-packages/rediscluster/connection.py" in get_master_node_by_slot
  333.         return self.nodes.slots[slot][0]

Exception Type: KeyError at /account/continue/
Exception Value: 12873
```

**Comment by melinath** [comment] 2018-10-18 17:21
node.slots for one user has 5461 entries, all of which point to the master node.

**Comment by melinath** [comment] 2018-10-18 17:28
One user with a working setup has 16384, which point to various nodes in the cluster.

**Comment by Grokzen** [comment] 2018-10-18 20:16
Okey, that makes kinda sense based on the stack trace and what you are describing according to the number of entries.

If you look at your config inside your redis cluster, do you run with the following config set to no?
```
cluster-require-full-coverage <yes/no>: If this is set to yes, as it is by default, the cluster stops accepting writes if some percentage of the key space is not covered by any node. If the option is set to no, the cluster will still serve queries even if only requests about a subset of keys can be processed.
```
or do you perhaps run with this input parameter to the StrictRedisCluster instance set to True? https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L146 or are you rolling your own or do the django cache layer/app run it's own connection pool somehow that might do some iffy things? I guess not beucase you are inside the connection.py class, but just to clarify.

In the case where you would see only 5461 entries in your slots cache, it means that your cluster is broken for whatever reason that i can't really tell why. But it is, you probably had a working cluster at one point, then it split or disconnected for some reason and that master got disconnected or lost itself from the remaining pool. Then what is interesting is that your redis client have still managed to query the master node for its view of the redis clusters current slots config and state and got back something that it deems valid and the client have accepted that. The client should only accept this based on the 2 things i mentioned above. I guess best would be to add the config value to the cluster, or not to use the internal flag.

By default, your client should throw up an exception when it reaches this code https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L259 and i expect that you should get there when your client at some point runs the initialize method where it tries to do a cluster discovery to get the slots state.

If possible, try to dig deeper into the redis logs or why the cluster is broken. If you for example would be using my docker-redis-clsuter git repo as your redis cluster, i have seen at very rare occations instances where the cluster would not be joined at boot for yet unknown reason that would cause the same kind of errors that you have, but i usually reach this code https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L245 or get `CLUSTER DOWN` exceptionn thrown back to me.

**Comment by melinath** [comment] 2018-10-18 21:09
We're using the [`django_redis`](https://github.com/niwinz/django-redis/) library and your docker-redis-cluster container.

Client class: rediscluster.StrictRedisCluster
Connection pool class: rediscluster.connection.ClusterConnectionPool

We're passing `skip_full_coverage_check=True` to the connection pool on instantiation. If we turn it off for a user experiencing the clusterdown issue then they get:

```
RedisClusterException: All slots are not covered after query all startup_nodes
```

**Comment by Grokzen** [comment] 2018-10-18 21:17
Then you really need to investigate what the issue is with the redis cluster itself and why you do not get a working cluster up and running, or why it splits after it has been joined. I would say that this is not an issue for this lib by this point as the lib itself behaves as expected from my pov with the current config and when using that flag

I will close this issue as this error is not realted to this library code. If you find something more concreat inside the dockerfile that causes the issue, then please open up a new issue over in the docker repo instead. I would suggest that you do a cleanout of any old containers and built images from the local cache of the person that has issues with his container, and try to do a full rebuild of the container to sort out the join issue. Also try to inspect the logs output from the container to see if there is any output that could indicate why one or more of the nodes spit from the cluster.

**Closed by Grokzen** 2018-10-18 21:17 UTC
