### ISSUE TITLE
Update lib to support redis-py up to 3.5.x release

### ISSUE THREAD

**Issue by aasifalam** [Grokzen/redis-py-cluster#342] opened 2019-10-25 13:37 UTC
I want to move to latest version of redis-py (3.3.x) version. However I don't see supporting version with redis-py-cluster. 
I see that the latest version only supports till <3.1.0
Asif

**Comment by stpierre** [comment] 2019-11-21 16:21
I see that the code in master looks like it's support redis-py 3.3.x. When can we expect a new release?

Our specific use case is Celery, which requires redis-py>=3.2, but we can't use that with redis-py-cluster.

**Comment by Grokzen** [comment] 2019-11-21 19:15
As mentioned in other issues that raised the same issue

When developing the latest major release of this client lib, the goal was to get to 3.0.0 at least so the new features in there could be used. Due to the many changes in 3.1.x and above i decided not to take that in the same release as the work to port everything would be to great in one big batch. Release 2.1.0 aims to support up to latest in 3.3.x release. If you check the latest commit in the master branch, you can build a version that allows you to use any release in the 3.x.x track, but i think that the code is broken when using anything above 3.1.x.

**Comment by Grokzen** [comment] 2019-11-21 19:17
Yes you can try a newer release of redis-py from the master branch, but it is not fully compatible or working fully yet and there is still a bunch of code and stuff that needs to be ported into this code-base from upstream releases of redis-py before it can work properly.

**Comment by stpierre** [comment] 2019-11-21 19:20
Just to make sure I understand before I do anything rash like fork a library: There's no way currently to use redis-py-cluster==2.0.0 -- the only version that includes working Redis SSL support -- with Celery, and it's going to be a long while before there is a way?

**Comment by Grokzen** [comment] 2019-11-21 19:22
Celery requires 3.2.x+ and it is not supported in the 2.0.0 release no. And it is not just a matter of changing the upstream requirement either as it do not work at all when i tried it myself due to internal changes inside redis-py that needs to be ported here as well.

**Comment by aboganas** [comment] 2019-12-15 07:39
Any updates when the Release 2.1.0 will be out?
Celery blocking us from using redis-py-cluster==2.0.0

**Comment by Grokzen** [comment] 2019-12-16 20:29
@aboganas As it stands right now, not much or possibly very little work will be done during the holliday period. In Jan my work schedule frees up so i got plenty of time to put into this to get 2.1.0 out the door

**Comment by aboganas** [comment] 2020-02-12 09:58
any updates when as to expect the new 2.1.0  release to be out

**Comment by Grokzen** [comment] 2020-02-12 16:01
I am very close to cut a rc release of 2.1.0 basically all relevant tests now pass but there is still some small parts to go through and see if there needs to be a port into here. I dont have a installation or example or test scenario that runs it against a more normal use-case like in AWS or with celery.

**Comment by Grokzen** [comment] 2020-02-12 16:02
For anyone that want to give the code a spin, the master branch should be good enough now to use directly as a dependency that git could download and run to test if the release is good/stable enough to be cut into a proper 2.1.0 release.

**Comment by lfshammu** [comment] 2020-02-27 18:25
Master branch has been working well for me so far! would love to get a proper release so I can pin the version.

**Comment by Grokzen** [comment] 2020-03-03 18:24
@lfshammu I am pathcing up all the changes from the 3.4.x release. As soon as i have ported up all the changes from there i will make a RC release that can be tested out for those who dare to use it :)

**Comment by hradilf** [comment] 2020-03-06 06:37
@Grokzen Hi, please, will you support redis-py 3.4.1 with fixed username usage (Redis 6 ACL)? Then issue #327 could be fixed also as part of it, right? Thank you.

**Comment by Grokzen** [comment] 2020-03-06 09:14
@hradilf Right this moment, ACL commands is blocked out from the RedisCluster class. I have no idea how they work and how they work inside a clustered envrionment where the cluster lib itself have no idea what to do with each configuration style command.

My current idea that i am thinking about is to split all config commands into two seperate classes where the old RedisCluster client class will have all the configuratio ncommands blocked out hard to avoid any issues by accidentally calling ACL, Sentinel, Config, Cluster commands etc. And then have some kind of RedisClusterManagement class where all of these sever management stuff is located.

Also a side note, redis-server 6.0 is still in RC1 phase and i do not see any proper documentation up on redis.io yet describing these commands and how they are suppoesd to be used.

**Comment by itamarhaber** [comment] 2020-03-10 17:55
>  I have no idea how they work and how they work inside a clustered envrionment 

AMA!

If that helps anyone, ACL is just like any other configuration command in the cluster, i.e. they are local to the currently-conntected-to-server... similar to `CONFIG SET requirepass foobared`.

**Comment by bohea** [comment] 2020-04-03 08:00
waiting for 2.1.0, is there any todo list?

**Comment by IAmATeaPot418** [comment] 2020-04-14 04:40
@Grokzen - ACL Commands are probably extremely relevant to a clustered deployment, but nice to have for simplicity of deployment. They functionally would allow you to configure ACL users that can be used with Redis and persist them to the redis.conf file equivalent aclfile.

1. MasterAUTH now has an ACL companion that is functionally the same as a directive, called MasterUser. This ACL user can now be used to authenticate a replica to a master.
2. AUTH now has 2 arguments rather than 1, a username and a password.

Documentation is in progress but the best current documentation can be found here: https://redis.io/topics/acl

**Comment by Grokzen** [comment] 2020-05-22 13:22
For anyone finidng this issue, a 2.1.0-RC1 release has now been published https://github.com/Grokzen/redis-py-cluster/releases/tag/untagged-1c535719fd292631a171

This release will be active here on github for no more then 1 week before 2.1.0 final will be cut and released properly. Like stated in the release page, this release will not be published on pypi so it will only be accessible from downloading directly from github.

For anyone who finds any issues or problems with that RC release, please open up a new issue here on github describing what the problem is. If there is no major blockers a release will be out within 1 week give or take.

**Comment by itamarhaber** [comment] 2020-05-22 13:25
Awesome @Grokzen - plz fix the tag as it is 404ing

**Comment by Grokzen** [comment] 2020-05-22 13:29
Link updated

**Comment by gfronza** [comment] 2020-05-22 13:29
This is great news! thanks @Grokzen!

**Comment by aboganas** [comment] 2020-05-22 14:07
great news thanks @Grokzen

**Comment by AvnerCohen** [comment] 2020-05-25 06:01
Can anyone confirm initial usage in production?

**Comment by johntmyers** [comment] 2020-06-25 21:19
Hi, any update here since the 22 May mention of the RC being avail then cutting 2.1.0?

**Comment by Grokzen** [comment] 2020-06-26 08:29
@johntmyers I have been working on some of the issues that has been presented that is blocking for a proper release. I am going on vacation after today so i will wrap it up as soon as possible so it dont drag out for much longer now.

**Comment by eltoder** [comment] 2020-07-23 13:39
@Grokzen Can you publish this version to pypi as a release candidate[1]? This will give people an easy way to try it out, but it will not be installed by default.

[1] https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning

**Comment by farzad-xgen** [comment] 2020-07-29 12:42
When do you think the new release will be on PyPI? We recently switched to use Celery, and we have a Redis cluster in production, but Celery needs redis>=3.2.0 and current stable release on PyPi (2.0.0) doesn't support that.

**Comment by farzad-xgen** [comment] 2020-08-03 06:51
I'm a bit worried, @Grokzen has gone radio silent since Jun 26th. Are you OK?

**Comment by holmboe** [comment] 2020-08-03 07:54
It is holiday season in Sweden in July so it is to be expected to not be as active during this time.

**Comment by Grokzen** [comment] 2020-08-03 18:31
@farzad-xgen I have not gone totally radio silent, but like holmboe said, there is vacation period right now but it is over now so i am about to get back to everything and get this one out the door as it has been a long time comming now.

**Comment by farzad-xgen** [comment] 2020-08-03 19:35
> @farzad-xgen I have not gone totally radio silent, but like holmboe said, there is vacation period right now but it is over now so i am about to get back to everything and get this one out the door as it has been a long time comming now.

Glad to hear that! I hope you enjoyed your holiday. Iveas worried a bit with these all pandemic things.

**Comment by farzad-xgen** [comment] 2020-08-09 09:40
Hi, any updates?

**Comment by farzad-xgen** [comment] 2020-09-11 23:44
Hi, any updates?

**Comment by Grokzen** [comment] 2020-09-18 08:40
I will drop the RC2 release tonight on pypi properly this time and then i am finishing up the documentation changes i have in the pipeline and then the final release will be made.

**Comment by Grokzen** [comment] 2020-09-19 07:44
RC2 release has been uploaded to pypi now https://pypi.org/manage/project/redis-py-cluster/release/2.0.99rc2/

To upgrade an existing installation to pre release or install a new environment from scratch you can run the following ` pip install redis-py-cluster redis -U --pre`

Final release will come shortly

**Comment by Grokzen** [comment] 2020-09-25 23:31
2.1.0 is now released into the wild

https://pypi.org/project/redis-py-cluster/2.1.0/
https://github.com/Grokzen/redis-py-cluster/releases/tag/2.1.0

For any bugs and/or issues in that release, please open up a new issue.

**Closed by Grokzen** 2020-09-25 23:31 UTC

**Comment by AvnerCohen** [comment] 2020-09-26 12:08
@Grokzen Thank you so much for doing this and completing this milestone!
