### ISSUE TITLE
Can I get a redis-py-cluster==2.1.0 by `setup.py install redis-py-cluster`?

### ISSUE THREAD

**Issue by HaozhengLi** [Grokzen/redis-py-cluster#348] opened 2020-01-08 03:31 UTC
Hi.

I need to use redis-py (3.3.x), cuz the new version fix some important BUGs, about the connection_pool:
https://github.com/Grokzen/redis-py-cluster/issues/182
https://github.com/andymccurdy/redis-py/issues/306
https://github.com/andymccurdy/redis-py/pull/886

But redis-py-cluster==2.0.0 does not support it.

So I install redis-py-cluster==2.1.0 by `setup.py install redis-py-cluster`.

It does work. I get redis-py-cluster==2.1.0, redis==3.3.11.

But I still meet the same BUG.

My question is, did I do a wrong 2.1.0 install by using `setup.py install redis-py-cluster`? And it makes the redis==3.3.11 not working as well.

Or did redis==3.3.11 has not fix these BUGs actually?

That is to say, can I get a redis-py-cluster==2.1.0 by `setup.py install redis-py-cluster`?

Thank you very much.

**Comment by Grokzen** [comment] 2020-01-08 11:50
Duplicate of #342 See the mentioned bug for why the master branch is broken and not fully compatible with redis-py yet.

**Closed by Grokzen** 2020-01-08 11:50 UTC
