### ISSUE TITLE
password arg not works.

### ISSUE THREAD

**Issue by hanbaga** [Grokzen/redis-py-cluster#131] opened 2016-03-14 11:54 UTC
1.   redis-7000.conf

masterauth Qunar@2005
requirepass Qunar@2005

and other redis.conf is the same one

2.  redis client code

        _startup_nodes = [
            dict(host=node.split(':')[0], port=int(node.split(':')[1]))
            for node in CONF.REDIS.nodes
        ]
        try:
            self.redis = StrictRedisCluster(
                startup_nodes=_startup_nodes,
                decode_responses=True,
                password= "Qunar@2005"
            )
        except Exception as ex:
            print 'except, ', str(ex)

3.   redis-cli works to authenticate password. 

/home/q/redis/src/redis-cli -h 10.88.183.51 -p 7000 -c -a Qunar@2005
10.88.183.51:7000> set a b
-> Redirected to slot [15495] located at 10.88.183.241:7003
OK

4. but error occur using redis-py-cluster
ERROR sending 'cluster slots' command to redis server: {'host': '10.88.183.51', 'port': 7000}

5.   it works if not set auth info between client code and configure file.  

help me to handle the password issue. thanks a lot

**Comment by Grokzen** [comment] 2016-03-14 13:04
It would be bad because there is travis tests that runs on password protected cluster nodes to test just that support. If it is reproducible then it would mean a major defect.

If possible, could you try to reproduce the problem on a different installation or machine all together  just to be extra sure?

**Comment by hanbaga** [comment] 2016-03-14 13:11
I reproduce the problem  when set protected-mode no

**Comment by hanbaga** [comment] 2016-03-14 13:15
I find a issue about code

    def get_redis_link(self, host, port, decode_responses=False):
        return StrictRedis(host=host, port=port, decode_responses=decode_responses)

password is not set as param of StrictRedis.

**Comment by hanbaga** [comment] 2016-03-14 13:16
the version is 1.1.0

**Comment by hanbaga** [comment] 2016-03-15 00:51
when to release new version. @Grokzen

**Comment by mrochford** [comment] 2016-03-25 13:19
I am seeing the same issue where the password is not being set in 1.1.0 release.

**Comment by Grokzen** [comment] 2016-03-28 17:32
@hanbaga I can confirm that it works as intended in unstable and that i can run the following code with a cluster that is password protected

```python
from rediscluster import StrictRedisCluster

startup_nodes = [{"host": "127.0.0.1", "port": "7100"}]

# Note: decode_responses must be set to True when used with python3
rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True, password= "abc123")
rc.get("foobar")
```

and it works as i expect.

The only thing that i can complain about in the unstable branch is that the exception that is raised when wrong password is provided.

A note about the mentioned `get_redis_link`. It sure looks abit wierd right now that i do not explicitly send in a password field or something.  If you look in this variable https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L20 you see that the password is sent into the nodemanager and is preserved for any connection to a redis node that is made from inside the nodemanager. Inside the `get_redis_link` method https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/nodemanager.py#L103 you find that the connection kwargs is sent along into the acctual redis connection object and the password is sent along in there.

To make a long story short, i will close this issue when i make the next release and i do not have an ETA when that will be right now.

**Comment by Grokzen** [comment] 2016-03-28 17:45
Just a note, it was implemented in this commit 5f66761c4dbf7b686f17ad3b90f172e92f004cf8

**Comment by Grokzen** [comment] 2016-03-29 21:22
Closing this as fixed/implemented and it will be part of next release.

**Closed by Grokzen** 2016-03-29 21:22 UTC
Labels: Fixed In next release

**Comment by qianShaw** [comment] 2019-01-04 03:35
sorry ,i want to ask about how to client redis cluster with password, now I  can client redis single with password

**Comment by Grokzen** [comment] 2019-01-04 13:18
@lostsquirrel Look at the example a few comments up. Or try the same method as you do in a normal redis-py instance and it should work out the same.

**Comment by qianShaw** [comment] 2019-01-05 08:42
OK，i got it ，thank you for your reply. Happy new year!

发自我的 iPhone
