### ISSUE TITLE
TTL exhausted

### ISSUE THREAD

**Issue by 15astro** [Grokzen/redis-py-cluster#301] opened 2019-01-02 17:47 UTC
I am frequently facing TTL exhausted error with the recent version of this redis-py-cluster driver. 
There seem to be some timeouts before TTL depending on maxRedirects. Many of the operations on redis being executed within micro or milliseconds. 

The socket_timeout and socket_connect_timeout is set to 2.0.

There isn't any change in the cluster slots allocation just to reduce the possibility of MOVED errors.

What are the possible causes?

Redis version 4.0.11.

@Grokzen

**Comment by Grokzen** [comment] 2019-01-03 00:04
This is an common question/problem that occurs rather frequently. The basic symptome that happens is that you get stuck in this exception loop https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/client.py#L403 . The logic here is that if the client can't deliver the commands you have said you want to have delivered, it will fail out after a certain number of attempts. One very common problem here is the issue where your cluster tracks your nodes to 127.0.0.1 but your clients is connecting on an external IP 172.x.x.x range and the client gets back from the cluster "hey i am over at 127.0.0.1" so the client tries to connect to it but fails and then TTL issue is raised.

The only thing that i can provide help with is that you must instrument all the try/except blocks inside this method `def execute_command(self, *args, **kwargs):` to see what error it gets stuck inside. I basically need to know if you get stuck in a ASK/MOVED loop, or a timeout loop. Since you have a specific timeout set, i simply thing that you get into a wierd random loop in case of a timeout.

**Comment by 15astro** [comment] 2019-01-03 14:04
Thanks, @Grokzen.
> The logic here is that if the client can't deliver the commands you have said you want to have delivered, it will fail out after a certain number of attempts. One very common problem here is the issue where your cluster tracks your nodes to 127.0.0.1 but your clients is connecting on an external IP 172.x.x.x range and the client gets back from the cluster "hey i am over at 127.0.0.1" so the client tries to connect to it but fails and then TTL issue is raised
- This is not the case here.

> The only thing that i can provide help with is that you must instrument all the try/except blocks inside this method def execute_command(self, *args, **kwargs): to see what error it gets stuck inside. I basically need to know if you get stuck in a ASK/MOVED loop, or a timeout loop. Since you have a specific timeout set, i simply thing that you get into a wierd random loop in case of a timeout

- Added logs to client.py to find out what's causing the Timeout Error:
  ```except (ConnectionError, TimeoutError) as e:
                log.info("Printing Exception:%s"%e)
                try_random_node = True
                log.info("Its connection or Timeout error")
                log.info("Timeout Error => attempt = %s"%ttl)
                if ttl < self.RedisClusterRequestTTL / 2:```

 -  Following error is shown in logs: 
  `Error while reading from socket: ('Connection closed by server.',)`

**Comment by Grokzen** [comment] 2019-01-03 14:41
In that case/error this client behaves as expected and this is more on the Operations side of things over some bug/issue in the client. Either your server died, your network failed or your socket timeout out. I will close this one as invalid as this is not a bug/issue with the client itself. But you need to figure out what is happening with your redis server itself as the issue seems to be on it's way to it.

**Closed by Grokzen** 2019-01-03 14:41 UTC

**Comment by hkaraoguz** [comment] 2020-01-07 09:20
> The logic here is that if the client can't deliver the commands you have said you want to have delivered, it will fail out after a certain number of attempts. One very common problem here is the issue where your cluster tracks your nodes to 127.0.0.1 but your clients is connecting on an external IP 172.x.x.x range and the client gets back from the cluster "hey i am over at 127.0.0.1" so the client tries to connect to it but fails and then TTL issue is raised.

I am frequently facing the TTL exhausted issue within the Docker environment on my Mac. In my setup, I have two Docker containers. The first one runs the redis cluster which is using the latest image you have provided at [docker-redis-cluster](https://github.com/Grokzen/docker-redis-cluster). The second one runs my own code that executes tests for redis operations. The tests normally succeed but they randomly fail due to TTL exhausted error. I have tried the same setup without Docker and I did not receive the error so far.

I think you have mentioned a verbal solution for Docker platform somewhere but I couldn't fully understand how to do that. Thank you.

**Comment by Grokzen** [comment] 2020-01-07 09:23
Do you get the TTL error right away? or do you get it after a while and you have sent some commands to the server already?

**Comment by hkaraoguz** [comment] 2020-01-07 09:46
During the test I have two hgetall commands. I think it always crashes on the second hgetall. I guess it can reach the cluster once but fails in the second.

**Comment by Grokzen** [comment] 2020-01-07 09:48
Are you fully sure that you can reach it once and then fails? I would doubt that and say that it fails all of the time, please test to make it fully sure. Also if this is the case, then this question is something for the docker repo and not this repo as it would not be an error in this client.  If you are running on Mac, the solution is this section in the readme for the repo https://github.com/Grokzen/docker-redis-cluster#important-for-mac-users

**Comment by hkaraoguz** [comment] 2020-01-07 10:00
Yes I am sure it can reach because time to time all tests succeed and I can see that hash key is inserted to the cluster. Problem is that it randomly receives ttl exhausted error and this happens only on Docker platform. 

> If you are running on Mac, the solution is this section in the readme for the repo https://github.com/Grokzen/docker-redis-cluster#important-for-mac-users

I already applied that and I think that part works as expected. I thought my issue could be related to IP tracking problem that you mentioned in Docker but I do not know how to configure that within Docker.

**Comment by Grokzen** [comment] 2020-01-07 10:05
Then you have to dig deeper into this client code on your side to track down what type of error you are getting. The client itself should not just blow up on its own if you have a consistent and stable execution flow of commands into the server and then boom it breaks. The client responds to an event of some sort, you have to look in the main client loop to see what state that breaks and causes a TTL loop error.

**Comment by hkaraoguz** [comment] 2020-01-07 12:27
I think the problem lies within the MacOS Docker network limitations. I have tried different things:
1. Running the redis cluster and the code in native environment. Everything works
2. Running the latest docker image of [docker-redis-cluster](https://github.com/Grokzen/docker-redis-cluster) as a container and running the test code in native environment. Everything works
3. Running the latest docker image of [docker-redis-cluster](https://github.com/Grokzen/docker-redis-cluster) and my own test code as Docker containers. Random but frequent TTL exhausted error. 

I am not sure how to debug this within Docker but I just wanted to inform you about my findings.

**Comment by Grokzen** [comment] 2020-01-07 12:29
I am sorry i can't provide you with any further help, i know about the mac network problems that they do exists. But since i do not have a mac at hand to run/test anything, i can't provide any futher information and help to solve your specific issue. Since the problem is inside your docker installation, it is not an issue for this repo and probably not for docker-redis-cluster git repo either but docker itself.

**Comment by hkaraoguz** [comment] 2020-01-08 09:42
Just an update, when I start a redis cluster in docker with this script https://gist.github.com/abhirockzz/c08dbc479da0ccf4412d039ad9a548d1#file-create-redis-cluster-sh
 it works without any problems in Docker environment. I guess a private network setup that is implemented in that script somehow solves the issues in Docker environment.
