### ISSUE TITLE
HGETALL return long type value

### ISSUE THREAD

**Issue by huwei88** [Grokzen/redis-py-cluster#155] opened 2016-08-26 07:43 UTC
I deployed a redis cluster with six nodes. And saved a hashmap into it. All redis.conf "timeout" options is 600. All logical are working as expected when my app connect to this cluster using redis-py-cluster. But after one night, I got the following exception( it is a part of the traceback).

NOTE: I have retried to get this key by redis-cli, it is OK. And I checked all redis cluster nodes log(debug level), no error and warning message found.

```
res = self.redis_conn.hgetall(res_id)
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/client.py", line 1861, in hgetall
  return self.execute_command('HGETALL', name)
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/utils.py", line 93, in inner
  return func(*args, **kwargs)
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/client.py", line 309, in execute_command
  return self.parse_response(r, command, **kwargs)
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/client.py", line 587, in parse_response
  return self.response_callbacks[command_name](response, **options)
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/client.py", line 338, in <lambda>
  'HGETALL': lambda r: r and pairs_to_dict(r) or {},
File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/client.py", line 186, in pairs_to_dict
  it = iter(response)
TypeError: 'long' object is not iterable
```

**Comment by huwei88** [comment] 2016-08-26 07:48
Not sure it is a bug or relate to redis-py-cluster, maybe its relate to redis timeout option, because I did not hit this exception when do not change redis.conf timeout option. But also not sure. :(

**Comment by Grokzen** [comment] 2016-08-26 19:25
@huwei88 The exception is inside the `client.py` class so you need to dig further into the code and the data you get back in order to be able to determine what the problem is. The return data is wrong type but without knowing what kind of data was returned, it is difficult to determiine what the problem is or how to fix it.

An easy way to try to replicate this problem if it is the timeout that causing this is to set it down to something like 1 second and try to force the same error multiple of times and look on and post the response data it tries to parse.

**Comment by huwei88** [comment] 2016-08-29 02:24
Thanks @Grokzen, I tried to find the return value. But there's no log in client.py (I can  not log those keys in my code for some reasons),  seems I have to hack this code and add some log here. However, I'm sure the value of this key in redis is hashmap.

I also tried to set the timeout option to 5s, and add pdb in the code, sadly, but everything is ok. During this debug, I used 'netstate' to check the connection between client and redis. And found that redis server closed the socket connection after 5s. But I can get redis data(using redis-py-cluster client by pdb) after 10s or longer by the same redis connection which stored in connection pool.

I'll try to get the return value when hit the same issue, and paste the result here.

**Comment by huwei88** [comment] 2016-08-29 02:38
'NoneType' object has no attribute 'readline'
  Traceback (most recent call last):
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/neutron/services/vpc/cache_drvier/driver_manager.py", line 66, in safe_sync_redis
      rt_data = getattr(self.driver, fun)(context, *args, **kwargs)
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/neutron/services/vpc/cache_drvier/redis_driver.py", line 210, in save_vif
      p.execute()
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/pipeline.py", line 100, in execute
      return self.send_cluster_commands(stack, raise_on_error)
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/utils.py", line 93, in inner
      return func(*args, **kwargs)
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/pipeline.py", line 210, in send_cluster_commands
      n.read()
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/rediscluster/pipeline.py", line 466, in read
      c.result = self.parse_response(connection, c.args[0], **c.options)
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
      response = connection.read_response()
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
      response = self._parser.read_response()
    File "/opt/ksc_lbaas/.venv/lib/python2.7/site-packages/redis/connection.py", line 238, in read_response
      response = self._buffer.readline()
  AttributeError: 'NoneType' object has no attribute 'readline'

This is another exception, which followed by the former one, but with another key. I think those exceptions can have the same root cause.

**Comment by huwei88** [comment] 2016-08-31 01:20
Seems those issues are relate to Green Socket. I monkey patched socket in my app by eventlet. After I add a green thread lock, those issue disappeared. Green thread lock can make sure my method will not interrupt because of socket connection.

E.g.:
```
    @lock('lock_name')
    def save_vif(self, context, vif, association_list=[]):
        with self.redis_conn.pipeline() as p:
            if vif:
                vif = dict(vif)
                vif.pop('sg_uuid_list', None)
                p.hmset(vif.get('id'), vif)
                p.sadd(self._get_keyname(vif.get('vgw_host'), 'vifs'), vif.get('id'))
                p.sadd(self._get_keyname(vif.get('vnet_id'), 'vgws'), vif.get('vgw_host'))
                p.sadd(self._get_keyname(vif.get('domain_id'), 'vifs'), vif.get('id'))

            if association_list:
                p.delete(self._get_keyname(vif.get('id'), 'vifsguuids'))
                p.delete(self._get_keyname(vif.get('id'), 'vifsgids'))

                for vif_sg_association in association_list:
                    p.sadd(self._get_keyname(vif_sg_association.get('sg_uuid'), 'sgvifids'),
                           vif_sg_association.get('vif_id'))
                    p.sadd(self._get_keyname(vif_sg_association.get('vif_id'), 'vifsguuids'),
                           vif_sg_association.get('sg_uuid'))
                    p.sadd(self._get_keyname(vif_sg_association.get('vif_id'), 'vifsgids'),
                           vif_sg_association.get('sg_id'))
            p.execute()
```

**Comment by Grokzen** [comment] 2016-09-11 10:59
@huw Very interesting that you seem to remove the problem when you patch in a lock for the operation. That feels like it would be a threading problem with connections but i can't really say exactly where the problem would be if it is inside this client or redis-py client. But if a lock helps then it feels like the same connection object is used multiple of times and the built in locking mechanisms that exists in both clients must be looked at if something was missed or they are not working properly. Both clients should be thread safe in the core design.

**Comment by huwei88** [comment] 2016-09-12 06:55
I'm sorry to make a mistake. After I add some log in redis-py-cluster. I got the real error.
This issue should relate to redis-server socket close.  Line
https://github.com/Grokzen/redis-py-cluster/blob/unstable/rediscluster/pipeline.py#L466 got ConnectionError because client got empty socket data. See
https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L144. And because I use pipline, then some command can share the same connection. So if the former command got ConnnectionError, the socket and connection seems will be released. Then we get the "AttributeError: 'NoneType' object has no attribute 'readline'" exceptions.

Using lock reduce this issue reproduce times. But can not fix it. May be this is because of server's performance. And because I used lock, some requests have to be queued which reduced the redis server pressure.

However, I think redis-py-cluster should raise the real exception(ConnectionError) instead of AttributeError.@Grokzen.

**Comment by fossilet** [comment] 2016-11-04 06:57
It seems this has been fixed in v1.3.1.

**Comment by Grokzen** [comment] 2016-11-12 20:37
@huwei88 The following link is broken as of today, could you update it to the line you are refering to or change from unstable branch to a specific commit that makes it easier to see the line.

@huwei88 What version are you running your code on and is the code above a complete example that can reliably force the problem to appear?? Or can you verify that the latest code in unstable (to be 1.3.2) or the release 1.3.1 fixes your problem?

@fossilet Would you consider this issue closeable with that statement that it is fixed in 1.3.1?? I know that the pipeline class got a major rewrite in 1.3.1 so it might have goten improved or fixed even within that refactoring.

**Comment by fossilet** [comment] 2016-11-14 10:19
@Grokzen I use 1.3.1, and the AttributeError no longer occurs. I think it is probably fixed.

**Comment by Grokzen** [comment] 2016-11-14 14:26
@fossilet @huwei88 I will close this one as `Fixed in 1.3.1` for now and if you see this reappearing in future releases after 1.3.1 please open one new ticket with the new issue. Thanks for helping out @fossilet  :)

**Closed by Grokzen** 2016-11-14 14:26 UTC

**Comment by huwei88** [comment] 2016-11-15 07:42
@Grokzen I hit this issue in version 1.3 and 1.2. Finally, I resolved this issue by set timeout to zero and set tcp-keepalive to 60s. I'll test 1.3.1 when I have time, and open new ticket if it reoccur.

**Comment by jeffwidman** [comment] 2018-10-12 06:36
@huwei88 did you ever get a chance to test this again?

**Comment by huwei88** [comment] 2018-10-12 06:50
No, after I  set timeout to zero and tcp-keepalive to 60s in redis.conf, we did not hit this issue any more . And our service has already online 2 years.
