### ISSUE TITLE
Hash key containing ':' throws error

### ISSUE THREAD

**Issue by skreutzberger** [Grokzen/redis-py-cluster#74] opened 2015-06-04 11:41 UTC
If a hash key contains the character ':' then the following error is thrown under Python 2.7.9:

```
Traceback (most recent call last):
  File "redis-cluster-bug.py", line 21, in <module>
    rc.hmset(key, value_dict)
  File "/Users/sebastian/.virtualenvs/sea/lib/python2.7/site-packages/redis/client.py", line 1872, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/Users/sebastian/.virtualenvs/sea/lib/python2.7/site-packages/rediscluster/utils.py", line 82, in inner
    return func(*args, **kwargs)
  File "/Users/sebastian/.virtualenvs/sea/lib/python2.7/site-packages/rediscluster/client.py", line 301, in execute_command
    action = self.handle_cluster_command_exception(e)
  File "/Users/sebastian/.virtualenvs/sea/lib/python2.7/site-packages/rediscluster/client.py", line 154, in handle_cluster_command_exception
    raise e
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```

The same call is actually working when I use the redis-py library. I also checked to do the call directly in Redis-CLI and it works there, too. It seems you somewhere split the response using the ':' as  separator or so. But I could not find it in the codebase.

And a sample code which shows the issue (1 key works, 1 not):

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
shows a bug in redis-py-cluster which happens
if a hash name contains the ':' character
"""
cluster_nodes = [{"host": "127.0.0.1", "port": "30001"},]

from rediscluster import RedisCluster
rc = RedisCluster(startup_nodes=cluster_nodes, decode_responses=True)

value_dict = {'name': "Peter Meyer", "email": "peter@test.com", "age": 35}

for i in xrange(1000):

    key = str("test:foo:%d" % i) # breaks hmset call
    key = str("testfoo%d" % i) # works

    rc.hmset(key1, value_dict)

    resp = rc.hgetall(key)
    print "%s = %s " % (key, resp)

```

Is it easy to fix?

Thanks for bringing Python 3 Cluster support to Python!

Best regards,

Sebastian

**Comment by Grokzen** [comment] 2015-06-04 11:45
I will have a look at this later tonight after work :]

**Comment by Grokzen** [comment] 2015-06-04 12:26
From a quick look at it, i would suggest that you wipe all data in your redis instance and try only with the key that you think breaks. It could be that you already have data on that key that breaks. You should also run `TYPE <key>` on one of the failing keys to see what datatype is there right now and what is expected.

I also think that you should run MONITOR command while running to see if there is something wrong with the command that it is building. It might give some clues.

**Comment by skreutzberger** [comment] 2015-06-04 19:01
I did both and it still does not work, I flush the server (flushall) before I run the script. Can you reproduce the issue? Maybe it is caused by Python 2.7.9?

**Comment by Grokzen** [comment] 2015-06-05 06:11
So, i ran your code in python 2.7.6, 2.7.9, 3.4.1 and with both key types and it all works on my side. It can set and get your dict and print it to stdout just fine.

Did you try to run the `TYPE` command right after you ran your code to see what data is really there?

**Comment by Grokzen** [comment] 2015-06-09 19:45
@skreutzberger Any luck or update to this?

**Comment by Grokzen** [comment] 2015-07-11 05:53
@skreutzberger Any update to this? I can't reproduce the error on my side and i am going to close this issue for now. If you have any luck in helping me reproduce this then i you can open this issue again and we will continue from there. As far as i know this is expected behaviour from the client to return a error like the one you are getting but i can't figure out why it does this for you but not for me or any other.

**Closed by Grokzen** 2015-07-11 05:53 UTC
