### ISSUE TITLE
1.2.0 version failed with `TTL exhausted` ClusterError

### ISSUE THREAD

**Issue by misterion** [Grokzen/redis-py-cluster#141] opened 2016-04-12 12:53 UTC
Library failed with ClusterError `TTL exhausted` on `object` command:
```
self.redis.object(infotype='ENCODING', key=key)
````

The error stack

```
 File "D:\ProjectsGit\tools\redis-memory-analyzer\rma\scanner.py", line 78, in resolve_with_pipe
    obj_encoding = self.redis.object(infotype='ENCODING', key=key)
  File "D:\Linetools\Python35-32\lib\site-packages\redis\client.py", line 678, in object
    return self.execute_command('OBJECT', infotype, key, infotype=infotype)
  File "D:\Linetools\Python35-32\lib\site-packages\rediscluster\utils.py", line 93, in inner
    return func(*args, **kwargs)
  File "D:\Linetools\Python35-32\lib\site-packages\rediscluster\client.py", line 342, in execute_command
    raise ClusterError('TTL exhausted.')

rediscluster.exceptions.ClusterError: TTL exhausted.
```
And here the same simptoms as in #123

**Comment by Grokzen** [comment] 2016-07-04 12:28
@misterion Like i responded in the mentioned issue, i can't reproduce this problem reliably and in what situations this will cause problems. The `TTL exhausted` error is a very generic error that usually happens if the networks goes down or the client can't get in touch with the node it tries to talk to.

I have some ideas how to make the excpetion output more relevant information that can help to narrow down what the problem is. I will still close this one as i did with the previous one. Hopefully the situation will be better in release `1.3.0`.

**Closed by Grokzen** 2016-07-04 12:28 UTC
