### ISSUE TITLE
Automatically populating all of the startup nodes

### ISSUE THREAD

**Issue by maxblaze** [Grokzen/redis-py-cluster#172] opened 2016-12-13 20:50 UTC
With the "official" ruby redis cluster client library, you only need to specify a single startup node in order for the rest of the nodes to be discovered and populated. With the current version of redis-py-cluster failover will not occur to any nodes not in the original startup list. I was able to get around this by setting ``origin_startup_nodes`` as shown below, but is there a reason why this isn't the default behavior?

```
rc.connection_pool.nodes.populate_startup_nodes()
rc.connection_pool.nodes.orig_startup_nodes = rc.connection_pool.nodes.startup_nodes
```

**Comment by Grokzen** [comment] 2016-12-14 08:34
@maxblaze I need some more info then this to be able to understand and reproduce this problem. Do you have some kind of stacktrace of more detailed instructions on how to reproduce this and what you are seeing when you use it?

Or are you talking about the fact that when a failover happens it will try to re-query the cluster to get a new accurate status of the state of the cluster? If this is the case i do think this is intented behaviour as it is right now. I think the idea is that you build/provide for example a common DNS name to the lib and that should allways point to a node that is part of the cluster or where the cluster live. If you point it to a static IP then you have to ensure that there is allways a node there that will answer.

The thing is that there is a list of the "discovered nodes" already in place becuase without it the client would not work, but because of the mentioned logic above, that list is never persisted into the orig_startup_nodes.

**Comment by maxblaze** [comment] 2016-12-15 04:03
My use case is to have a round-robin DNS entry that will serve up a single address in the cluster. For my test setup I have a 6-node cluster (3 master nodes and 3 slaves) that was created with the following commands:
```cd redis-3.2.3/utils/create-cluster
./create-cluster stop
./create-cluster clean
./create-cluster start
yes yes | ./create-cluster create
```
Here is my test script, which connects to one of the master nodes:
```
#! /usr/bin/env python

from rediscluster import StrictRedisCluster
import time

startup_nodes = [{"host": "127.0.0.1", "port": "30001"}]

rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=True)
rc.connection_pool.nodes.populate_startup_nodes()

# The line in question
rc.connection_pool.nodes.orig_startup_nodes = rc.connection_pool.nodes.startup_nodes

x = 0
while 1:
        try:
                rc.set("foo" + str(x), "bar" + str(x))
                print(rc.get("foo" + str(x)))
                x = x + 1
                print rc.connection_pool.nodes.orig_startup_nodes
                time.sleep(.10)
        except Exception, e:
               print e
```

While this script is running I simply killed each master node in sequence beginning with the startup node. The client successfully recovers as long as `origin_startup_nodes` is set to `nodes.startup_nodes`. The following error triggers without this line and the client never recovers:
> Redis Cluster cannot be connected. Please provide at least one reachable node.

**Comment by maxblaze** [comment] 2017-01-04 21:23
@Grokzen Any luck reproducing this, or is this expected behavior?

**Comment by Grokzen** [comment] 2017-02-05 18:30
@maxblaze I would say that this is indeed the expected behaviour based on what the reference implementation has defined. I am not sure exactly what to do here becuase i have not runned a big cluster in prod mode yet so i do not know the best practises on how to operate a cluster and how to handle node outages.

My gut feeling says that allowing the clients to allow for the drift and detect it by itself and correct it and ignoring all startup nodes is probably not the way to go forward.

It would be great if you could find some references to other cluster enabled clients and how they deal with this problem. If they use the original nodes or if they use the detected nodes and handles the drift each time a node fails.

**Comment by Grokzen** [comment] 2017-03-05 14:32
@maxblaze Please see this commit for a possible solution to your problem 13503d9954456882a70580750464885ac8540b3f

Please note that it is experimental and i still think that the already normal approach is to let DNS deal with the nodes moving around instead of letting the cluster tracking it. But if that is how you think you will handle the problem best, then it is up to you.

Closing this one as fixed/implemented. If you get any problems with the feature please open a new issue.

**Closed by Grokzen** 2017-03-05 14:32 UTC

**Comment by redpintings** [comment] 2020-05-13 05:46
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/client.py", line 205, in __init__
    pool = connection_pool_cls(
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/connection.py", line 146, in __init__
    self.nodes.initialize()
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/nodemanager.py", line 231, in initialize
    raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.

Who can tell me why?

**Comment by redpintings** [comment] 2020-05-13 05:48
[root@localhost ~]# python3
Python 3.8.2 (default, Apr 20 2020, 10:10:11) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rediscluster import RedisCluster
>>> nodes = [{"host": "127.xx.x.xxx", "port": "xxxx"}]
>>> rs = RedisCluster(startup_nodes=nodes, decode_responses=True, skip_full_coverage_check=True, password='xxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/client.py", line 205, in __init__
    pool = connection_pool_cls(
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/connection.py", line 146, in __init__
    self.nodes.initialize()
  File "/opt/python3/lib/python3.8/site-packages/rediscluster/nodemanager.py", line 231, in initialize
    raise RedisClusterException("Redis Cluster cannot be connected. Please provide at least one reachable node.")
rediscluster.exceptions.RedisClusterException: Redis Cluster cannot be connected. Please provide at least one reachable node.

Who can tell me why? I want help

**Comment by Grokzen** [comment] 2020-05-13 06:56
@redpintings The error says exactly what is the error, your node can't be connected to. Either you have the wrong ip:port or wrong password. Try to connect to the redis cluster with redis-cli first to get the connection details correct.
