### ISSUE TITLE
Object encoding fails with ClusterError: TTL exhausted error

### ISSUE THREAD

**Issue by misterion** [Grokzen/redis-py-cluster#123] opened 2016-02-18 14:10 UTC
From 1.1.0 version. From time to time my test script fails with ClusterError: TTL exhausted error with code like this:
```
 key_with_types = []
for key in ret:
      obj_encoding = self.redis.object(infotype='ENCODING', key=key)
      obj_type = self.redis.type(key)
       key_with_types.append({'type': obj_type, 'encoding': obj_encoding})
```

This happens always with any values of reinitialize_steps. From library source i see that execution tree in `client.py` always goes with that case then i got this error:
![c6703-clip-81kb](https://cloud.githubusercontent.com/assets/196737/13145474/fed1f740-d661-11e5-93f2-3ccb78d9d0c5.png)

1. Seng `Object encoding` command
2. Catch `MoveError`
3. Select `redirect_addr`
4. Try again

Actually `redirect_addr` will never be never used in this while loop. The `AskError` will never be catched becouse of `asking` variable will never be True in this loop. 

The dirty fix (and i do not know is this correct) is set asking=True if `refresh_table_asap` happens.

**Comment by 72squared** [comment] 2016-03-11 20:31
I know this logic has been rewritten in the unstable branch so I'm not sure if it is constructive to spend too much time on this. Maybe test out the unstable branch and see if you still get the issue? However, looking at the code you highlighted, it should be setting the correct slot in the line above your number 3.

```
self.connection_pool.nodes.slots[e.slot_id][0] = node

```

so that when it hits 4, it shoudl be using the node returned in the MovedError.

**Comment by Grokzen** [comment] 2016-03-28 22:01
@misterion I would agree with @72squared on this issue. You should really try to recreate this problem with the unstable branch and report back if you see the exact same problem or not. If you find the same issue then i can dig deeper into this and try to replicate this locally on my machine also and take it from there.

**Comment by Grokzen** [comment] 2016-03-28 22:10
One thing i found is that the `redirect_addr` variable is useless and affects nothing in this case. That variable is used further down in the `AskError` code path so it can be removed. It affected nothing for any of the tests for example.

**Comment by Grokzen** [comment] 2016-03-28 22:17
@misterion One thing that you could have got into is some wierd edge case where `reinitialize_steps` is working against you maybe. I would suggest you to try settings `reinitialize_steps` to some lower value then the default 25. 

One other possibility that i now remember is that i remember i have seen this similar problem before in a scenario when i used a docker container. What happened was that the `cluster slots` reported back `127.0.0.1` because all nodes was talking to each other inside the docker container on that IP but i would access them from my client outside docker and when i got a MOVED/ASK error it would update the nodes/slots tracking to point to a IP:PORT that was not accessible from outside docker.

At least it behaved similar but i can't say for sure what the root cause of the problem without more data on the problem.

**Comment by Grokzen** [comment] 2016-04-09 09:50
@misterion I will close this one because i can't reproduce any error based on the information provided here. Like mentioned by @72squared the logic has been rewriten for release 1.2.0 and if you can reproduce the same or similar error in the new release, please open a new tickets with all information you can provide.

**Closed by Grokzen** 2016-04-09 09:50 UTC

**Comment by trtg** [comment] 2018-04-28 00:59
@Grokzen you referenced an issue I've run into with a cluster brought up with docker via your other repo:
https://github.com/Grokzen/docker-redis-cluster 
cluster slots is indeed returning 127.0.0.1 so in my docker-compose setup the other container on the same network attempting to reach the cluster fails with connection refused on 127.0.0.1 where it should be using the host name of the container running the cluster. Even after hacking redis-py-cluster to do that I'm now running into "ClusterError: TTL exhausted." 
Do you have any recommendations for bringing up a cluster with docker that is compatible with redis-py-cluster, assuming I want to reach the cluster from another container in the same compose file?

**Comment by Grokzen** [comment] 2018-04-29 12:56
@trtg I do not. This is kinda a major problem of redis and how it handles the cluster discovery. But again, it was never designed for anything other then running it in isolation by itself. You probably have to hack around the `CLUSTER MEET` command and to provide compatible names that would resolve to IP addresses that is accessible from the outside or other containers.

**Comment by trtg** [comment] 2018-05-03 00:13
@Grokzen What I ended up doing- which may or not be helpful to you was to just bring up a single node with cluster-enabled yes in its redis.conf and nothing else. Once it was up I ran:
```
for i in `seq 0 16383`; do redis-cli -c -h my-cluster cluster addslots $i; done
```
I just needed a node with cluster semantics, to mimic our production stack, I didn't actually need a multiple node cluster, so this approach seemed to work fine, all other containers in my compose setup can talk to the node in question. I wonder (but did not test it) if it's possible to set redis.conf to bind to a hostname rather than to an IP, i.e.:
```
bind my-cluster
```
in the redis.conf ^^^^ in hopes that it would make cluster slots return a hostname rather than 127.0.0.1

**Comment by pq-dong** [comment] 2019-03-26 09:45
Hi,The 'TTL' error occurred in docker container but on windows the program has no error.
Program use Django:
setting:
```
        "BACKEND": "utils.cache.MyRedisCache",
        "LOCATION": [f"{REDIS_URL}:{REDIS_PORT1}/{db}",
                     f"{REDIS_URL}:{REDIS_PORT2}/{db}",
                     f"{REDIS_URL}:{REDIS_PORT3}/{db}"],
        "TIMEOUT": 300,
        "KEY_PREFIX": "oj",
        "DEFAULT_TIMEOUT": 300,
        "VERSION": 1,
        "KEY_FUNCTION": make_key,
        "OPTIONS": {
            'REDIS_CLIENT_CLASS': 'rediscluster.RedisCluster',
            'CONNECTION_POOL_CLASS': 'rediscluster.connection.ClusterConnectionPool',
        }
```
requirements:
```
django==1.11.20
django-redis==4.7.0
redis==2.10.6
redis-py-cluster==1.3.6
```

On my windows laptop it has no error and run normally but when it run at ubuntu the 'TTL' error occurred. i use docker-compose run it on ubuntu, so i think maybe the network can not connection，but when i run `netstat -ap`, it does connection. 
```
tcp        0      0 3bed1a4d58f2:45394      host:18021 ESTABLISHED -
tcp        0      0 3bed1a4d58f2:41526      host:18022 TIME_WAIT   -
tcp        0      0 3bed1a4d58f2:41318      host:18022 TIME_WAIT   -
tcp        0      0 3bed1a4d58f2:42172      host:18022 ESTABLISHED -
tcp        0      0 3bed1a4d58f2:45726      host:18021 ESTABLISHED -
tcp        0      0 3bed1a4d58f2:41840      host:18022 ESTABLISHED -
tcp        0      0 3bed1a4d58f2:41436      host:18022 TIME_WAIT   -
tcp        0      0 3bed1a4d58f2:47194      host:18020 TIME_WAIT   -
.........
```

so i want to know whether the rediscluster client is different between ubuntu and windows, occurred the program on windows is normal but on ubuntu is fail

**Comment by Grokzen** [comment] 2019-03-26 11:44
@pq-dong This is not a issuissue with this lib, the issue is that you are running the redis servers inside docker and when you do that, then redis will track the docker ip address that is inside the container and when your client connects to each server, redis returns to the client that "all nodes are here, here and over here" and if you connect your client from outside the machine that docker runs on, it will not know where your cluster is when it tries to resolve the ip address of the docker container. The difference between systems might be what IP address that the docker container exposes or binds to it's internal cluster state.
