### ISSUE TITLE
AttributeError: 'ClusterParser' object has no attribute '_reader'

### ISSUE THREAD

**Issue by baranbartu** [Grokzen/redis-py-cluster#168] opened 2016-11-17 13:28 UTC
Hello @Grokzen ,

Let me give some details about our scenario;

15 API server with 200 gunicorn processes
each process has one redis cluster client initialized with max_connection=2**7 and socket_timeout=4
redis cluster with 10 master redis-server which each of them is 15 GB.

problem is about pipeline something like below,
pipeline = client.pipeline()
pipeline.hmset(key1,mapping)
pipeline.hmset(key2,mapping)
...
..
.
pipeline.execute()

So, i have just changed stream parser with Hiredis,
before adding Hiredis, we were using standart PythonParser and was getting similar error like below,
**NoneType' object has no attribute 'readline'**

So, somehow we are getting this error and i could not reproduce on my local even i use multithreads and share pipeline instance between threads. 

Do you have any idea whether it is about our architectural design or known issue with redis client?

Thanks in advance.

**Comment by Grokzen** [comment] 2016-11-17 15:13
@baranbartu I could use some extra info. What version of this client are you running? What version of Hiredis? and can you provide a full stacktrace of the problem?

I know i have seen this problem before but i need some additional information to help narrow it down some.

**Comment by baranbartu** [comment] 2016-11-18 07:32
@Grokzen,

>> pip freeze | grep redis
`hiredis==0.2.0
redis==2.10.5
redis-py-cluster==1.2.0`

And you can find whole details on below sentry link.

https://sentry.io/share/issue/36353438382e313832343639383638/

**Comment by Grokzen** [comment] 2016-11-18 11:54
@baranbartu What i remember is that in #155 there was a similar issue with threading and error handling in the last itteration of pipeline code. In release 1.3.1 the error handling code was rewritten and it have fixed some of the error handling logic.

I would suggest that you try to upgrade or test the release 1.3.1 out and see if that changes anything. I know that your stack trace is abit different but maybe it will help. The only solution that i have seen for people that experience problems with multithreading solutions was to add locks but that will severly affect performance and usability but atleast they got the problem away from their code. It might however be a canary that there is something wrong with the multi threading support or solution that is in either of the libs hiredis, redis or redis-py-cluster that makes the operations safe to use in threading envs.

I am not really sure how to proceed otherwise.

**Comment by baranbartu** [comment] 2016-11-18 12:22
@Grokzen it won't be easy to bump cluster client version on our side since different exceptions we may get because of high volume traffic, but thanks, i am going to try somehow.

**Comment by Grokzen** [comment] 2016-11-18 12:31
The one thing that i am stuck on the exception message that says AttributeError: 'ClusterParser' object has no attribute '_reader'` where it mentions that the clusterparser object fails. I do think that it might be related to hiredis. You probably should start to look into what happens with the clusterparser object and why it do not contain the `_reader` variable and attack the problem from that angle.  It might be some dynamic code that is added or how that part works, i am not really sure.

It feels like that multiple threads is messing with the same object from my previous experience with the same type of problems that have been reported. Either that the second thread is trying to use an object that it expects to have data in it that an earlier thread already consumed and deconstructed. Or it is the earlier thread that tries to read from what it think is its object but someone else have messed with it or is trying to build/set new values.

**Comment by Grokzen** [comment] 2017-02-08 20:03
@baranbartu Any update to this issue? Been a while now.

**Comment by Grokzen** [comment] 2017-03-05 14:06
@baranbartu Bump

**Comment by hitigon** [comment] 2017-07-30 02:46
@Grokzen I was hitting this error `NoneType' object has no attribute 'readline'` randomly with latest redis-py, redis-py-cluster, rq, uwsgi (multi-process, multi-threads) recently. Since rq uses pipeline to enqueue jobs, I believe it's a similar situation as @baranbartu's post. 

I'm trying to reproduce on local (docker, actually), but no luck so far.

**Comment by Grokzen** [comment] 2017-08-10 14:08
@hitigon Usually those errors is realted to threads and multi-processes. Since we do have much extra code for pipelines over the default implementation in redis-py there is a possibility that we have some issue in our code that is not fully thread safe in some situations. I have yet to see this kind of error in a none pipeline code path yet, but pipelines probably is the cause.

**Comment by Grokzen** [comment] 2018-03-13 21:15
Closing this issue due to lack of information and reproducability. If anyone can provide some reliable reproduce code then please reopen the issue and post it, or open a new issue and i can investigate further.

**Closed by Grokzen** 2018-03-13 21:15 UTC
